name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit-tests:
    name: run unit tests
    runs-on: ubuntu-20.04
    if: ${{ github.repository == 'sermojohn/codecov-devstaff21' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '1.17'
      - name: test
        run: make test-cover
      - uses: codecov/codecov-action@v2.0.3
        with:
          files: ./coverage.out # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          # flags: unittests # optional
